# Generated by Django 6.1 on 2026-09-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adminrole_coupon_homepagebanner_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='app.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_scope',
            field=models.CharField(choices=[('all', 'All Products / Entire Order'), ('category', 'Specific Category')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_auto_apply',
            field=models.BooleanField(default=False, help_text='If True, auto-applies without needing coupon code'),
        ),
    ]
