# Generated by Django 6.1 on 2026-09-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coupon_category_coupon_discount_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Main Hero Carousel'), ('product_spotlight', 'Featured Product Spotlight'), ('category_promo', 'Category Promotion Banner'), ('announcement', 'Top Announcement Bar')], default='hero', max_length=30),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='linked_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_banners', to='app.category'),
        ),
        migrations.AddField(
            model_name='homepagebanner',
            name='linked_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotional_banners', to='app.product'),
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Free delivery on Electronics above ₹2000', max_length=150)),
                ('rule_type', models.CharField(choices=[('storewide', 'Storewide Threshold'), ('category', 'Category-Specific'), ('product', 'Product-Specific'), ('city', 'City / Location-Specific')], default='storewide', max_length=20)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value for this rule', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee (0 for FREE delivery)', max_digits=10)),
                ('city', models.CharField(blank=True, help_text='e.g. Bengaluru, Mumbai (leave empty for any city)', max_length=100)),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = evaluated first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='app.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rules', to='app.product')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
    ]
