# Generated by Django 6.1 on 2026-09-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_homepagebanner_banner_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('local', 'Built-in Local AI Engine (Heuristic / No API Key Needed)'), ('openai', 'OpenAI (GPT-4o, GPT-4o-mini, o3-mini)'), ('openrouter', 'OpenRouter (Multi-model Router)'), ('gemini', 'Google Gemini (Gemini 2.0 Flash, Gemini 1.5 Pro)'), ('claude', 'Anthropic Claude (Claude 3.5 Sonnet, Claude 3.5 Haiku)'), ('groq', 'Groq (Llama 3.3 70B, Mixtral 8x7B)'), ('grok', 'xAI Grok (Grok-2, Grok-beta)')], default='local', max_length=30)),
                ('api_key', models.CharField(blank=True, help_text='API secret key for selected provider', max_length=255)),
                ('model_name', models.CharField(default='default', help_text='Specific model identifier (e.g. gpt-4o, gemini-2.0-flash, claude-3-5-sonnet-20241022)', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
