# Generated by Django 6.1 on 2026-09-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aiproviderconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderconfig',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional key expiration date', null=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message or status from provider'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='rate_limit_hit',
            field=models.BooleanField(default=False, help_text='True if 429 rate limit was encountered'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, help_text='Total successful API calls made'),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Not Verified'), ('valid', 'Valid / Operational'), ('invalid', 'Invalid Key'), ('rate_limited', 'Rate Limit Exceeded'), ('expired', 'Key Expired')], default='unverified', max_length=20),
        ),
    ]
