# Generated by Django 6.1 on 2026-09-02 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aiproviderconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiproviderconfig',
            options={'ordering': ['priority', '-updated_at']},
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='feature_scope',
            field=models.CharField(choices=[('all', 'All AI Features (Compare, Chatbot, Search Rescue)'), ('compare', 'Product Comparison Only'), ('chatbot', 'AI Shopping Assistant Chat Only'), ('search', 'Complex Search Rescue Only')], default='all', help_text='When to use this provider', max_length=20),
        ),
        migrations.AddField(
            model_name='aiproviderconfig',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Priority rank: 1 is Primary, 2 is 1st Fallback, 3 is 2nd Fallback...'),
        ),
    ]
