# Generated by Django 6.1 on 2026-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aiproviderconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiproviderconfig',
            name='feature_scope',
            field=models.CharField(default='all', help_text="When to use this provider (comma-separated or 'all')", max_length=100),
        ),
    ]
