# Generated by Django 6.1 on 2026-09-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_aiproviderconfig_feature_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_ai_exposed',
            field=models.BooleanField(default=False, help_text='If True, AI can suggest and expose this coupon code to customers'),
        ),
    ]
