# Generated by Django 6.1 on 2026-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_order_gateway_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Delivery PIN / Postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='shippingrule',
            name='pincode',
            field=models.CharField(blank=True, help_text='e.g. 560034, 560001, 110001 (or comma-separated PINs)', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='label',
            field=models.CharField(help_text='e.g. Free delivery on PIN 560034 or Karnataka Express', max_length=150),
        ),
        migrations.AlterField(
            model_name='shippingrule',
            name='rule_type',
            field=models.CharField(choices=[('storewide', 'Storewide Threshold'), ('pincode', 'Postal Code / PIN Code Specific'), ('category', 'Category-Specific'), ('product', 'Product-Specific'), ('city', 'City / Location-Specific (Fallback)')], default='storewide', max_length=20),
        ),
    ]
