# Generated by Django 6.1 on 2026-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_order_postal_code_shippingrule_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrule',
            name='pincode',
            field=models.CharField(blank=True, help_text='e.g. 560034, 560001, 110001 (or comma-separated PINs)', max_length=255),
        ),
    ]
