# Generated by Django 6.1 on 2026-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shippingrule_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='homepagebanner',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
